language: node_js
group: deprecated-2017Q4
services: 
  - mongodb
env:
  global:
    - MONGODB_VERSION=4.2.6
before_script:
  - cp config/secrets.json.example config/secrets.json
  - openssl req -x509 -newkey rsa:2048 -keyout config/key.pem -out config/cert.pem -days 365 -nodes -subj "/O=Aggie"
