version: '3'

services:
  mongo:
    container_name: mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'
  aggie:
    container_name: aggie
    links: 
      - 'mongo'
    depends_on:
      - 'mongo'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_CONNECTION_URL=mongodb://mongo:27017/aggie 
